env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/prop-types:
    - warn
  no-unused-vars:
    - warn
  react/jsx-key:
    - warn
  no-prototype-builtins:
    - warn
#  indent:
#    - error
#    - 2
#  linebreak-style:
#    - error
#    - unix
#  quotes:
#    - error
#    - single
#  semi:
#    - error
#    - always
#  react/jsx-uses-react:
#    - error
#  react/jsx-uses-vars:
#    - error
