FROM node:15-buster as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine as prod-build
COPY --from=build /app/build /usr/share/nginx/html
COPY docker/nginx/front.conf /etc/nginx/conf.d/default.conf
COPY docker/entryscripts/env_vars.sh /env_vars.sh
EXPOSE 80
CMD ["sh", "/env_vars.sh"]
